[tasks."releez:changelog:regen"]
run = "mise exec -- releez changelog regenerate"

[tasks."releez:build"]
run = """
rm -rf dist
uv build
ls -lh dist/
"""

[tasks."releez:publish"]
run = "uv publish dist/*"
