from pydantic import Field, computed_field
from repolish import BaseContext, BaseInputs


class WorkspaceProviderContext(BaseContext):
    """Context for the WorkspaceProvider."""

    workspace_ref: str = 'master'
    python_ref: str = 'master'
    enable_docs: bool = False
    has_python: bool | None = None
    python_operating_systems: list[str] = Field(
        default_factory=lambda: ['ubuntu-latest'],
    )
    python_codecov: bool = False

    @computed_field
    @property
    def generated_header(self) -> str:
        """Return the standard header used by this provider's templates."""
        raw_member_name = self.repolish.provider.session.member_name
        member_name = '' if raw_member_name in ('_root', '') else raw_member_name
        project_name = self.repolish.provider.project_name
        slug = f'{project_name}(in {member_name})' if member_name else project_name
        package_info = f'{slug}@{self.repolish.provider.version}'
        return f'generated by {package_info} - manual changes may be overwritten'


class WorkspaceProviderInputs(BaseInputs):
    """Inputs for the WorkspaceProvider.

    Fields declared here can be populated by other providers via
    ``provide_inputs`` and delivered to this provider's ``finalize_context``.
    """

    python_ref: str
