from pathlib import Path

import pytest
from devkit.releez.repolish.models import ReleezProviderContext
from devkit.workspace.repolish.models import WorkspaceProviderContext
from repolish.testing import make_context


@pytest.mark.parametrize(
    ('context_type', 'project_name'),
    [
        (WorkspaceProviderContext, 'hotdogwerx-devkit-workspace'),
        (ReleezProviderContext, 'hotdogwerx-devkit-releez'),
    ],
)
@pytest.mark.parametrize(
    ('member_name', 'expected_slug'),
    [
        ('_root', None),
        ('', None),
        ('package-a', 'package-a'),
    ],
)
def test_generated_header_uses_provider_metadata(
    context_type,
    project_name,
    member_name,
    expected_slug,
) -> None:
    """Generated headers identify the provider version and optional workspace member."""
    repolish_context = make_context(version='1.2.3')
    repolish_context.provider.project_name = project_name
    repolish_context.provider.session.member_name = member_name
    context = context_type(repolish=repolish_context)
    slug = f'{project_name}(in {expected_slug})' if expected_slug is not None else project_name

    assert context.generated_header == (f'generated by {slug}@1.2.3 - manual changes may be overwritten')


def test_managed_workflow_templates_share_generated_header() -> None:
    """Every provider-managed workflow delegates its header to the context property."""
    packages_dir = Path(__file__).parents[1] / 'packages'
    workflow_templates = list(
        packages_dir.glob(
            'devkit-*/devkit/*/resources/templates/repolish/.github/workflows/*.jinja',
        )
    )

    assert len(workflow_templates) == 5
    assert all(template.read_text().splitlines()[0] == '# {{ generated_header }}' for template in workflow_templates)
