from pydantic import computed_field
from repolish import BaseContext, BaseInputs


class ReleezProviderContext(BaseContext):
    """Context for the ReleezProvider."""

    releez_ref: str = 'master'
    build_command: str = 'uv build --no-sources'
    publish_command: str = 'uv publish dist/*'
    package_prefix: str = ''
    use_self_action: bool = False
    # Some consumers only want tagging/changelog/GitHub Release behavior,
    # without a Python package build and publish step.
    publish_package: bool = True

    @computed_field
    @property
    def generated_header(self) -> str:
        """Return the standard header used by this provider's templates."""
        raw_member_name = self.repolish.provider.session.member_name
        member_name = '' if raw_member_name in ('_root', '') else raw_member_name
        project_name = self.repolish.provider.project_name
        slug = f'{project_name}(in {member_name})' if member_name else project_name
        package_info = f'{slug}@{self.repolish.provider.version}'
        return f'generated by {package_info} - manual changes may be overwritten'


class ReleezProviderInputs(BaseInputs):
    """Inputs for the ReleezProvider (no cross-provider inputs used yet)."""
